// nexus-nuxt-2.3.0/pages/(admin)/ui/charts/apex/column/index.vue
<script setup lang="ts">
import DumbbellColumnChart from "./DumbbellColumnChart.vue";
import NegativeValuesColumnChart from "./NegativeValuesColumnChart.vue";
import RangeColumnChart from "./RangeColumnChart.vue";
import StackedColumnChart from "./StackedColumnChart.vue";

definePageMeta({
    layout: "admin",
});
</script>

<template>
    <div>
        <PageTitle title="Column Charts" :items="[{ label: 'Apex Charts' }, { label: 'Column', active: true }]" />

        <div class="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Stacked Column</div>
                    <StackedColumnChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Dumbbell Column</div>
                    <DumbbellColumnChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Range Column</div>
                    <RangeColumnChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Negative Values Column</div>
                    <NegativeValuesColumnChart />
                </div>
            </div>
        </div>
    </div>
</template>

// nexus-nextjs-2.3.0/src/app/(admin)/ui/charts/apex/column/page.tsx
import type { Metadata } from "next";

import { PageTitle } from "@/components/PageTitle";

import { DumbbellColumnChart } from "./DumbbellColumnChart";
import { NegativeValuesColumnChart } from "./NegativeValuesColumnChart";
import { RangeColumnChart } from "./RangeColumnChart";
import { StackedColumnChart } from "./StackedColumnChart";

export const metadata: Metadata = {
    title: "Apex Column Charts",
};

const ChartPage = () => {
    return (
        <>
            <PageTitle title="Column Charts" items={[{ label: "Apex Charts" }, { label: "Column", active: true }]} />
            <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Stacked Column</div>
                        <StackedColumnChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Dumbbell Column</div>
                        <DumbbellColumnChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Range Column</div>
                        <RangeColumnChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Negative Values Column</div>
                        <NegativeValuesColumnChart />
                    </div>
                </div>
            </div>
        </>
    );
};

export default ChartPage;
