// nexus-react@3.0.0/src/pages/admin/dashboards/gen-ai/components/ResourceUtilizationCard.tsx
import { ResourceUtilizationChart } from "./ResourceUtilizationChart";

export const ResourceUtilizationCard = () => {
    return (
        <div aria-label="Card" className="card bg-base-100 shadow">
            <div className="card-body p-0">
                <div className="flex items-center gap-3 px-5 pt-5">
                    <span className="iconify lucide--cpu size-4.5" />
                    <span className="font-medium">Resource Utilization</span>
                    <button className="btn btn-outline border-base-300 max-sm:btn-square btn-sm ms-auto">
                        <span className="iconify lucide--bar-chart size-3.5" />
                        <span className="max-sm:hidden">View Report</span>
                    </button>
                </div>
            </div>
            <ResourceUtilizationChart />
        </div>
    );
};

// nexus-sveltekit-2.3.0/src/routes/(admin)/dashboards/gen-ai/components/ResourceUtilizationCard.svelte
<script>
    import ResourceUtilizationChart from "./ResourceUtilizationChart.svelte";
</script>

<div aria-label="Card" class="card bg-base-100 shadow">
    <div class="card-body p-0">
        <div class="flex items-center gap-3 px-5 pt-5">
            <span class="iconify lucide--cpu size-4.5" />
            <span class="font-medium">Resource Utilization</span>
            <button class="btn btn-outline border-base-300 max-sm:btn-square btn-sm ms-auto">
                <span class="iconify lucide--bar-chart size-3.5" />
                <span class="max-sm:hidden">View Report</span>
            </button>
        </div>
    </div>
    <ResourceUtilizationChart />
</div>
