// nexus-nuxt-2.3.0/components/admin/SidebarMenuItem.vue
<script lang="ts" setup>
import type { NuxtLinkProps } from "#app/components/nuxt-link";

import SidebarMenuItemBadges, { type ISidebarMenuItemBadges } from "./SidebarMenuItemBadges.vue";

export interface ISidebarMenuItem {
    id: string;
    icon?: string;
    label: string;
    isTitle?: boolean;
    url?: string;
    linkProp?: NuxtLinkProps;
    children?: ISidebarMenuItem[];
    badges?: ISidebarMenuItemBadges["badges"];
}

const props = defineProps<ISidebarMenuItem & { activated: Set<string> }>();

const selected = computed(() => props.activated.has(props.id));
</script>

<template>
    <p v-if="props.isTitle" class="sidebar-menu-title">{{ props.label }}</p>

    <template v-else-if="!props.children">
        <NuxtLink
            :href="props.url ?? ''"
            class="sidebar-menu-item"
            :class="{ active: selected }"
            v-bind="props.linkProp">
            <span v-if="props.icon" class="iconify" :class="[props.icon, 'size-4']" />
            <span class="grow">{{ props.label }}</span>
            <SidebarMenuItemBadges :badges="props.badges" />
        </NuxtLink>
    </template>

    <template v-else>
        <div class="group collapse">
            <input
                aria-label="Sidemenu item trigger"
                type="checkbox"
                name="sidebar-menu-parent-item"
                :checked="selected"
                class="peer" />
            <div class="collapse-title">
                <span v-if="props.icon" class="iconify" :class="[props.icon, 'size-4']" />
                <span class="grow">{{ props.label }}</span>
                <SidebarMenuItemBadges :badges="props.badges" />
                <span class="iconify lucide--chevron-right arrow-icon size-3.5" />
            </div>
            <div class="collapse-content">
                <SidebarMenuItem
                    v-for="(item, index) in props.children"
                    :key="index"
                    v-bind="item"
                    :activated="props.activated" />
            </div>
        </div>
    </template>
</template>

// nexus-nextjs-2.3.0/src/app/(admin)/(layout)/components/SidebarMenuItem.tsx
import Link from "next/link";
import { AnchorHTMLAttributes } from "react";

import { ISidebarMenuItemBadges, SidebarMenuItemBadges } from "./SidebarMenuItemBadges";

export type ISidebarMenuItem = {
    id: string;
    icon?: string;
    label: string;
    isTitle?: boolean;
    url?: string;
    linkProp?: AnchorHTMLAttributes<HTMLAnchorElement>;
    children?: ISidebarMenuItem[];
} & ISidebarMenuItemBadges;

export const SidebarMenuItem = ({
    id,
    url,
    children,
    icon,
    isTitle,
    badges,
    linkProp,
    label,
    activated,
}: ISidebarMenuItem & { activated: Set<string> }) => {
    const selected = activated.has(id);

    if (isTitle) {
        return <p className="sidebar-menu-title">{label}</p>;
    }

    if (!children) {
        return (
            <Link href={url ?? ""} className={`sidebar-menu-item ${selected && "active"}`} {...linkProp}>
                {icon && <span className={`iconify ${icon} size-4`} />}
                <span className="grow">{label}</span>
                <SidebarMenuItemBadges badges={badges} />
            </Link>
        );
    }

    return (
        <div className="group collapse">
            <input
                aria-label="Sidemenu item trigger"
                type="checkbox"
                name="sidebar-menu-parent-item"
                defaultChecked={selected}
                className="peer"
            />
            <div className="collapse-title">
                {icon && <span className={`iconify ${icon} size-4`} />}
                <span className="grow">{label}</span>
                <SidebarMenuItemBadges badges={badges} />
                <span className="iconify lucide--chevron-right arrow-icon size-3.5" />
            </div>
            <div className="collapse-content">
                {children.map((item, index) => (
                    <SidebarMenuItem {...item} key={index} activated={activated} />
                ))}
            </div>
        </div>
    );
};
