// nexus-nuxt-2.3.0/pages/(admin)/apps/file-manager/(components)/StatItem.vue
<script lang="ts" setup>
export type IStatItem = {
    image: string;
    name: string;
    used: number;
    total: number;
    progressClass: string;
};

const props = defineProps<IStatItem>();
</script>

<template>
    <div class="card bg-base-100 cursor-pointer shadow transition-all hover:shadow-md">
        <div class="card-body p-4">
            <div class="bg-base-200 rounded-box w-fit p-2">
                <img :src="props.image" class="size-6" alt="" />
            </div>
            <div class="mt-3 flex items-center justify-between">
                <p class="text-sm font-medium">{{ props.name }}</p>
                <span class="text-base-content/80 text-xs"> {{ ((props.used * 100) / props.total).toFixed(0) }}% </span>
            </div>
            <progress
                class="progress mt-1.5 h-1.5"
                :class="props.progressClass"
                :max="props.total"
                :value="props.used"></progress>
            <div class="mt-1.5 flex items-center justify-between">
                <span class="text-sm font-medium">{{ props.used }} GB</span>
                <span class="text-base-content/80 text-xs">{{ props.total }} GB</span>
            </div>
        </div>
    </div>
</template>

// nexus-nextjs-2.3.0/src/app/(admin)/dashboards/ecommerce/components/StatItem.tsx
export type IStatItem = {
    title: string;
    amount: string;
    percent: number;
    icon: string;
    lastAmount: string;
};

export const StatItem = ({ title, percent, amount, lastAmount, icon }: IStatItem) => {
    return (
        <div className="card bg-base-100 shadow">
            <div className="card-body gap-2">
                <div className="flex items-start justify-between gap-2 text-sm">
                    <div>
                        <p className="text-base-content/80 font-medium">{title}</p>
                        <div className="mt-3 flex items-center gap-2">
                            <p className="inline text-2xl font-semibold">{amount}</p>
                            {percent > 0 ? (
                                <div className="badge badge-soft badge-success badge-sm gap-0.5 px-1 font-medium">
                                    <span className="iconify lucide--arrow-up size-3.5" />
                                    {percent}%
                                </div>
                            ) : (
                                <div className="badge badge-soft badge-error badge-sm gap-0.5 px-1 font-medium">
                                    <span className="iconify lucide--arrow-down size-3.5" />
                                    {percent}%
                                </div>
                            )}
                        </div>
                    </div>
                    <div className="bg-base-200 rounded-box flex items-center p-2">
                        <span className={`iconify size-5 ${icon}`} />
                    </div>
                </div>

                <p className="text-base-content/60 text-sm">
                    vs.<span className="mx-1">{lastAmount}</span>last period
                </p>
            </div>
        </div>
    );
};
