// nexus-react@3.0.0/src/pages/components/apex-charts/column/NegativeValuesColumnChart.tsx
import type { ApexOptions } from "apexcharts";
import { Suspense, lazy, useEffect, useState } from "react";

import { LoadingEffect } from "@/components/LoadingEffect";

const ApexCharts = lazy(() => import("react-apexcharts"));

const chartOptions: ApexOptions = {
    series: [
        {
            name: "Cash Flow",
            data: [
                1.45, 5.42, 5.9, -0.42, -12.6, -18.1, -18.2, -14.16, -11.1, -6.09, 0.34, 3.88, 13.07, 5.8, 2, 7.37, 8.1,
                13.57, 15.75, 17.1, 19.8, -27.03, -54.4, -47.2, -43.3, -18.6, -48.6, -41.1, -39.6, -37.6, -29.4, -21.4,
                -2.4,
            ],
        },
    ],
    chart: {
        type: "bar",
        height: 350,
        toolbar: {
            show: true,
            tools: {
                download: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
        },
    },
    plotOptions: {
        bar: {
            colors: {
                ranges: [
                    {
                        from: -1000,
                        to: -46,
                        color: "#FDA403",
                    },
                    {
                        from: -20,
                        to: 5,
                        color: "#A25772",
                    },
                    {
                        from: 5,
                        to: 1000,
                        color: "#167bff",
                    },
                ],
            },
            columnWidth: "80%",
        },
    },
    dataLabels: {
        enabled: false,
    },
    yaxis: {
        title: {
            text: "Growth",
        },
        labels: {
            formatter: function (y) {
                return y.toFixed(0) + "%";
            },
        },
    },
    xaxis: {
        type: "datetime",
        categories: [
            "2011-01-01",
            "2011-02-01",
            "2011-03-01",
            "2011-04-01",
            "2011-05-01",
            "2011-06-01",
            "2011-07-01",
            "2011-08-01",
            "2011-09-01",
            "2011-10-01",
            "2011-11-01",
            "2011-12-01",
            "2012-01-01",
            "2012-02-01",
            "2012-03-01",
            "2012-04-01",
            "2012-05-01",
            "2012-06-01",
            "2012-07-01",
            "2012-08-01",
            "2012-09-01",
            "2012-10-01",
            "2012-11-01",
            "2012-12-01",
            "2013-01-01",
            "2013-02-01",
            "2013-03-01",
            "2013-04-01",
            "2013-05-01",
            "2013-06-01",
            "2013-07-01",
            "2013-08-01",
            "2013-09-01",
        ],
        labels: {
            rotate: -90,
        },
    },
};

export const NegativeValuesColumnChart = () => {
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) return <LoadingEffect height={chartOptions.chart?.height} />;

    return (
        <Suspense fallback={<LoadingEffect height={chartOptions.chart?.height} />}>
            <ApexCharts
                options={chartOptions}
                type={chartOptions.chart?.type}
                height={chartOptions.chart?.height}
                series={chartOptions.series}
            />
        </Suspense>
    );
};

// nexus-nuxt-2.3.0/pages/(admin)/ui/charts/apex/column/NegativeValuesColumnChart.vue
<script setup lang="ts">
import type { ApexOptions } from "apexcharts";

const chartOptions: ApexOptions = {
    series: [
        {
            name: "Cash Flow",
            data: [
                1.45, 5.42, 5.9, -0.42, -12.6, -18.1, -18.2, -14.16, -11.1, -6.09, 0.34, 3.88, 13.07, 5.8, 2, 7.37, 8.1,
                13.57, 15.75, 17.1, 19.8, -27.03, -54.4, -47.2, -43.3, -18.6, -48.6, -41.1, -39.6, -37.6, -29.4, -21.4,
                -2.4,
            ],
        },
    ],
    chart: {
        type: "bar",
        height: 350,
        toolbar: {
            show: true,
            tools: {
                download: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
        },
    },
    plotOptions: {
        bar: {
            colors: {
                ranges: [
                    {
                        from: -1000,
                        to: -46,
                        color: "#FDA403",
                    },
                    {
                        from: -20,
                        to: 5,
                        color: "#A25772",
                    },
                    {
                        from: 5,
                        to: 1000,
                        color: "#167bff",
                    },
                ],
            },
            columnWidth: "80%",
        },
    },
    dataLabels: {
        enabled: false,
    },
    yaxis: {
        title: {
            text: "Growth",
        },
        labels: {
            formatter: function (y) {
                return y.toFixed(0) + "%";
            },
        },
    },
    colors: ["#167bff", "#FDA403"],

    xaxis: {
        type: "datetime",
        categories: [
            "2011-01-01",
            "2011-02-01",
            "2011-03-01",
            "2011-04-01",
            "2011-05-01",
            "2011-06-01",
            "2011-07-01",
            "2011-08-01",
            "2011-09-01",
            "2011-10-01",
            "2011-11-01",
            "2011-12-01",
            "2012-01-01",
            "2012-02-01",
            "2012-03-01",
            "2012-04-01",
            "2012-05-01",
            "2012-06-01",
            "2012-07-01",
            "2012-08-01",
            "2012-09-01",
            "2012-10-01",
            "2012-11-01",
            "2012-12-01",
            "2013-01-01",
            "2013-02-01",
            "2013-03-01",
            "2013-04-01",
            "2013-05-01",
            "2013-06-01",
            "2013-07-01",
            "2013-08-01",
            "2013-09-01",
        ],
        labels: {
            rotate: -90,
        },
    },
};

const chartRef = ref<HTMLDivElement | null>(null);
onMounted(async () => {
    const ApexCharts = (await import("apexcharts")).default;
    if (chartRef.value) {
        new ApexCharts(chartRef.value, chartOptions).render();
    }
});
</script>

<template>
    <div ref="chartRef"></div>
</template>
