// nexus-react@3.0.0/src/pages/admin/apps/file-manager/components/UploadButton.tsx
import { FileUploader } from "@/components/forms/FileUploader";

export const UploadButton = () => {
    return (
        <>
            <button
                className="btn btn-ghost border-base-300 btn-sm"
                aria-label="Upload file"
                onClick={() => document.querySelector<HTMLDialogElement>("#apps-file-upload-modal")?.showModal()}>
                <span className="iconify lucide--upload size-4" />
                Upload
            </button>
            <dialog id="apps-file-upload-modal" className="modal">
                <div className="modal-box">
                    <div className="flex items-center justify-between">
                        <p className="font-medium">Upload Files</p>
                        <form method="dialog">
                            <button className="btn btn-ghost btn-sm btn-circle" aria-label="Close upload file modal">
                                <span className="iconify lucide--x size-5" />
                            </button>
                        </form>
                    </div>
                    <div className="mt-4">
                        <FileUploader />
                        <div className="mt-5 text-end">
                            <button className="btn btn-primary btn-sm">
                                <span className="iconify lucide--arrow-down-to-line size-4" />
                                Import
                            </button>
                        </div>
                    </div>
                </div>
                <form method="dialog" className="modal-backdrop">
                    <button>close</button>
                </form>
            </dialog>
        </>
    );
};

// nexus-nuxt-2.3.0/pages/(admin)/apps/file-manager/(components)/UploadButton.vue
<script setup lang="ts">
import FileUploader from "~/components/forms/FileUploader.vue";

const modal = ref<HTMLDialogElement | null>(null);

const showModal = () => {
    modal.value?.showModal();
};

const closeModal = () => {
    modal.value?.close();
};
</script>

<template>
    <div>
        <button class="btn btn-ghost border-base-300 btn-sm" aria-label="Upload file" @click="showModal">
            <span class="iconify lucide--upload size-4"></span>
            Upload
        </button>

        <dialog id="apps-file-upload-modal" ref="modal" class="modal">
            <div class="modal-box">
                <div class="flex items-center justify-between">
                    <p class="font-medium">Upload Files</p>
                    <form method="dialog">
                        <button
                            class="btn btn-ghost btn-sm btn-circle"
                            aria-label="Close upload file modal"
                            @click="closeModal">
                            <span class="iconify lucide--x size-5"></span>
                        </button>
                    </form>
                </div>
                <div class="mt-4">
                    <FileUploader />
                    <div class="mt-5 text-end">
                        <button class="btn btn-primary btn-sm">
                            <span class="iconify lucide--arrow-down-to-line size-4"></span>
                            Import
                        </button>
                    </div>
                </div>
            </div>
            <form method="dialog" class="modal-backdrop" @click="closeModal">
                <button>close</button>
            </form>
        </dialog>
    </div>
</template>
