// nexus-react@3.0.0/src/pages/admin/apps/gen-ai/library/index.tsx
import { MetaData } from "@/components/MetaData";
import { PageTitle } from "@/components/PageTitle";

import { AiLibraryTable } from "./LibraryTable";

const AiLibraryPage = () => {
    return (
        <>
            <MetaData title="AI Library" />
            <PageTitle title="Library" items={[{ label: "Gen Ai" }, { label: "Library", active: true }]} />
            <div className="mt-6">
                <AiLibraryTable />
            </div>
        </>
    );
};

export default AiLibraryPage;

// nexus-sveltekit-2.3.0/src/routes/(admin)/apps/gen-ai/library/+page.svelte
<script lang="ts">
    import PageTitle from "$lib/components/PageTitle.svelte";
    import AiLibraryTable from "./AiLibraryTable.svelte";
</script>

<PageTitle title="Image Gen" items={[{ label: "Gen Ai" }, { label: "Image Gen", active: true }]} />

<div class="mt-6">
    <AiLibraryTable />
</div>
