// nexus-sveltekit-2.3.0/src/routes/landing/+page.svelte
<script lang="ts">
    import BundleOffer from "./components/BundleOffer.svelte";
    import CTA from "./components/CTA.svelte";
    import FAQ from "./components/FAQ.svelte";
    import FeatureList from "./components/Features.svelte";
    import Footer from "./components/Footer.svelte";
    import Hero from "./components/Hero.svelte";
    import Showcase from "./components/Showcase.svelte";
    import Testimonial from "./components/Testimonial.svelte";
    import Topbar from "./components/Topbar.svelte";
</script>

<div class="bg-[var(--layout-background)]">
    <Topbar />
    <Hero />
    <FeatureList />
    <Showcase />
    <Testimonial />
    <CTA />
    <FAQ />
    <BundleOffer />
    <Footer />
</div>

// nexus-react-2.3.0/src/pages/landing/index.tsx
import { MetaData } from "@/components/MetaData";

import { BundleOffer } from "./components/BundleOffer";
import { CTA } from "./components/CTA";
import { FAQ } from "./components/FAQ";
import { Features } from "./components/Features";
import { Footer } from "./components/Footer";
import { Hero } from "./components/Hero";
import { Showcase } from "./components/Showcase";
import { Testimonial } from "./components/Testimonial";
import { Topbar } from "./components/Topbar";

const LandingPage = () => {
    return (
        <>
            <MetaData />

            <div>
                <Topbar />
                <Hero />
                <Features />
                <Showcase />
                <Testimonial />
                <CTA />
                <FAQ />
                <BundleOffer />
                <Footer />
            </div>
        </>
    );
};

export default LandingPage;
