// nexus-nuxt-2.3.0/pages/(admin)/apps/ecommerce/orders/[id]/components/OrderItemsTableRow.vue
<script setup lang="ts">
export interface IOrderItemsTableRow {
    id: number;
    image: string;
    name: string;
    category: string;
    sku: string;
    price: number;
    quantity: number;
    totalAmount: number;
}

defineProps<IOrderItemsTableRow>();
</script>
<template>
    <tr>
        <th class="font-medium">{{ id }}</th>
        <td>
            <div class="flex items-center space-x-3 truncate">
                <img :src="image" alt="Product" class="size-10 rounded" />
                <div>
                    <p class="font-medium">{{ name }}</p>
                    <p class="text-base-content/60 text-xs">#{{ sku }}</p>
                </div>
            </div>
        </td>
        <td>{{ category }}</td>
        <td>\${{ price }}</td>
        <td>{{ quantity }}x</td>
        <td class="font-medium">\${{ totalAmount }}</td>
    </tr>
</template>

// nexus-react-2.3.0/src/pages/admin/apps/ecommerce/orders/edit/components/OrderItemsTableRow.tsx
export type IOrderItemsTableRow = {
    id: number;
    image: string;
    name: string;
    category: string;
    sku: string;
    price: number;
    quantity: number;
    totalAmount: number;
};

export const OrderItemsTableRow = ({
    id,
    image,
    name,
    category,
    price,
    quantity,
    sku,
    totalAmount,
}: IOrderItemsTableRow) => {
    return (
        <tr>
            <th className="font-medium">{id}</th>
            <td>
                <div className="flex items-center space-x-3 truncate">
                    <img alt="Product" className="size-10 rounded" src={image} />
                    <div>
                        <p className="font-medium">{name}</p>
                        <p className="text-base-content/60 text-xs">#{sku}</p>
                    </div>
                </div>
            </td>
            <td>{category}</td>
            <td>${price}</td>
            <td>{quantity}x</td>
            <td className="font-medium">${totalAmount}</td>
        </tr>
    );
};
