// nexus-react@3.0.0/src/pages/admin/apps/chat/components/ChatList.tsx
// @ts-ignore
import SimpleBar from "simplebar-react";

import { ChatItem, IChatItem } from "./ChatItem";

type IChatList = {
    chats: IChatItem[];
    selected: IChatItem;
    selectChat(chat: IChatItem): void;
};

export const ChatList = ({ chats, selected, selectChat }: IChatList) => {
    return (
        <div className="card bg-base-100 shadow">
            <div className="card-body">
                <div className="flex items-center justify-between gap-3">
                    <label className="input">
                        <span className="iconify lucide--search text-base-content/80 size-4" />
                        <input
                            type="search"
                            className="grow"
                            placeholder="Search along chats"
                            aria-label="Search chat"
                        />
                    </label>
                    <div className="tooltip" data-tip="New Contact">
                        <button className="btn btn-outline btn-square border-base-300" aria-label="Add New Contact">
                            <span className="iconify lucide--plus size-4" />
                        </button>
                    </div>
                </div>

                <SimpleBar className="h-[calc(100vh_-_306px)]">
                    <div className="mt-4">
                        {chats.map((chat, index) => (
                            <div onClick={() => selectChat(chat)} key={index}>
                                <ChatItem {...chat} selected={selected?.id == chat.id} />
                            </div>
                        ))}
                    </div>
                </SimpleBar>

                <div className="mt-3 text-center">
                    <button className="btn btn-soft btn-primary btn-sm">
                        <span className="iconify lucide--user-plus size-3.5" />
                        Join a Community
                    </button>
                </div>
            </div>
        </div>
    );
};

// nexus-nuxt-2.3.0/pages/(admin)/apps/chat/(components)/ChatList.vue
<script setup lang="ts">
// @ts-ignore
import SimpleBar from "simplebar";

import ChatItem from "./ChatItem.vue";
import type { IChatMessageItem } from "./ChatItem.vue";

interface IChatItem {
    id: number;
    image: string;
    name: string;
    messages: IChatMessageItem[];
    unreadCount?: number;
}

interface IChatList {
    chats: IChatItem[];
    selected: IChatItem;
    selectChat(chat: IChatItem): void;
}

defineProps<IChatList>();

const chatListRef = ref<HTMLDivElement | null>(null);

onMounted(() => {
    if (chatListRef.value) {
        new SimpleBar(chatListRef.value);
    }
});
</script>

<template>
    <div class="card bg-base-100 shadow">
        <div class="card-body">
            <div class="flex items-center justify-between gap-3">
                <label class="input">
                    <span class="iconify lucide--search text-base-content/80 size-4"></span>
                    <input aria-label="Search chat" class="grow" placeholder="Search along chats" type="search" />
                </label>
                <div class="tooltip" data-tip="New Contact">
                    <button aria-label="Add New Contact" class="btn btn-outline btn-square border-base-300">
                        <span class="iconify lucide--plus size-4"></span>
                    </button>
                </div>
            </div>

            <div ref="chatListRef" class="h-[calc(100vh_-_306px)]">
                <div class="mt-4">
                    <div v-for="(chat, index) in chats" :key="index" @click="selectChat(chat)">
                        <ChatItem
                            :image="chat.image"
                            :name="chat.name"
                            :messages="chat.messages"
                            :unread-count="chat.unreadCount"
                            :selected="selected?.id === chat.id" />
                    </div>
                </div>
            </div>

            <div class="mt-3 text-center">
                <button class="btn btn-soft btn-primary btn-sm">
                    <span class="iconify lucide--user-plus size-3.5"></span>
                    Join a Community
                </button>
            </div>
        </div>
    </div>
</template>
