// nexus-react-2.3.0/src/pages/admin/ui/forms/label/index.tsx
import { MetaData } from "@/components/MetaData";
import { PageTitle } from "@/components/PageTitle";

const FormLabelPage = () => {
    return (
        <>
            <MetaData title="Label - Forms" />
            <PageTitle title="Label" items={[{ label: "Forms" }, { label: "Label", active: true }]} />
            <div className="mt-6 grid gap-6 lg:grid-cols-2">
                <div className="card card-border bg-base-100">
                    <div className="card-body">
                        <div className="card-title">Prefix</div>
                        <div className="mt-4">
                            <label className="input">
                                <span className="label">https://</span>
                                <input type="text" placeholder="URL" />
                            </label>
                        </div>
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body">
                        <div className="card-title">Suffix</div>
                        <div className="mt-4">
                            <label className="input">
                                <input type="text" placeholder="domain name" />
                                <span className="label">.com</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body">
                        <div className="card-title">Select</div>
                        <div className="mt-4">
                            <label className="select">
                                <span className="label">Type</span>
                                <select>
                                    <option>Personal</option>
                                    <option>Business</option>
                                </select>
                            </label>
                        </div>
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body">
                        <div className="card-title">Date Input</div>
                        <div className="mt-4">
                            <label className="input">
                                <span className="label">Publish date</span>
                                <input type="date" />
                            </label>
                        </div>
                    </div>
                </div>
                <div className="card card-border bg-base-100 h-fit">
                    <div className="card-body">
                        <div className="card-title">Floating</div>
                        <div className="mt-4">
                            <label className="floating-label">
                                <span>Your name</span>
                                <input type="text" placeholder="Your name" className="input input-md" />
                            </label>
                        </div>
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body">
                        <div className="card-title">Size</div>
                        <div className="mt-4 flex flex-col gap-4">
                            <label className="floating-label">
                                <input type="text" placeholder="Extra Small" className="input input-xs" />
                                <span>Extra Small</span>
                            </label>
                            <label className="floating-label">
                                <input type="text" placeholder="Small" className="input input-sm" />
                                <span>Small</span>
                            </label>
                            <label className="floating-label">
                                <input type="text" placeholder="Medium" className="input input-md" />
                                <span>Medium</span>
                            </label>
                            <label className="floating-label">
                                <input type="text" placeholder="Large" className="input input-lg" />
                                <span>Large</span>
                            </label>
                            <label className="floating-label">
                                <input type="text" placeholder="Extra Large" className="input input-xl" />
                                <span>Extra Large</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default FormLabelPage;

// nexus-sveltekit-2.3.0/src/routes/(admin)/ui/forms/label/+page.svelte
<script lang="ts">
    import PageTitle from "$lib/components/PageTitle.svelte";
</script>

<div>
    <PageTitle title="Label" items={[{ label: "Forms" }, { label: "Label", active: true }]} />
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <div class="card card-border bg-base-100">
            <div class="card-body">
                <div class="card-title">Prefix</div>
                <div class="mt-4">
                    <label class="input">
                        <span class="label">https://</span>
                        <input type="text" placeholder="URL" />
                    </label>
                </div>
            </div>
        </div>
        <div class="card card-border bg-base-100">
            <div class="card-body">
                <div class="card-title">Suffix</div>
                <div class="mt-4">
                    <label class="input">
                        <input type="text" placeholder="domain name" />
                        <span class="label">.com</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="card card-border bg-base-100">
            <div class="card-body">
                <div class="card-title">Select</div>
                <div class="mt-4">
                    <label class="select">
                        <span class="label">Type</span>
                        <select>
                            <option>Personal</option>
                            <option>Business</option>
                        </select>
                    </label>
                </div>
            </div>
        </div>
        <div class="card card-border bg-base-100">
            <div class="card-body">
                <div class="card-title">Date Input</div>
                <div class="mt-4">
                    <label class="input">
                        <span class="label">Publish date</span>
                        <input type="date" />
                    </label>
                </div>
            </div>
        </div>
        <div class="card card-border bg-base-100 h-fit">
            <div class="card-body">
                <div class="card-title">Floating</div>
                <div class="mt-4">
                    <label class="floating-label">
                        <span>Your name</span>
                        <input type="text" placeholder="Your name" class="input input-md" />
                    </label>
                </div>
            </div>
        </div>
        <div class="card card-border bg-base-100">
            <div class="card-body">
                <div class="card-title">Size</div>
                <div class="mt-4 flex flex-col gap-4">
                    <label class="floating-label">
                        <input type="text" placeholder="Extra Small" class="input input-xs" />
                        <span>Extra Small</span>
                    </label>
                    <label class="floating-label">
                        <input type="text" placeholder="Small" class="input input-sm" />
                        <span>Small</span>
                    </label>
                    <label class="floating-label">
                        <input type="text" placeholder="Medium" class="input input-md" />
                        <span>Medium</span>
                    </label>
                    <label class="floating-label">
                        <input type="text" placeholder="Large" class="input input-lg" />
                        <span>Large</span>
                    </label>
                    <label class="floating-label">
                        <input type="text" placeholder="Extra Large" class="input input-xl" />
                        <span>Extra Large</span>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>
