// nexus-react@3.0.0/src/pages/admin/apps/ecommerce/sellers/create/CreateSellerForm.tsx
import React, { useState } from "react";
import { Link } from "react-router";

import { FileUploader } from "@/components/forms/FileUploader";

export const CreateSellerForm = () => {
    const [showPassword, setShowPassword] = useState(false);

    return (
        <div>
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                <div className="card bg-base-100 shadow">
                    <div className="card-body">
                        <div className="card-title">Basic Information</div>
                        <div className="fieldset mt-2 grid grid-cols-1 gap-4 lg:grid-cols-2">
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="name">
                                    Name
                                </label>
                                <input type="text" className="input w-full" placeholder="Name" id="name" />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label">Email</label>
                                <input type="email" className="input w-full" placeholder="Email" id="email" />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label">Mobile</label>
                                <input type="tel" className="input w-full" placeholder="(098) 765 4321" />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="DOB">
                                    DOB
                                </label>
                                <input type="date" className="input w-full" aria-label="DOB" id="DOB" />
                            </div>
                            <div className="flex items-center gap-3">
                                <input className="toggle toggle-sm" type="checkbox" id="verified" />
                                <label className="label" htmlFor="verified">
                                    Verified
                                </label>
                            </div>
                            <div className="flex items-center gap-3">
                                <input
                                    className="radio radio-sm"
                                    type="radio"
                                    value="male"
                                    defaultChecked
                                    name="apps-seller-gender"
                                    id="apps-seller-gender-male"
                                />
                                <label className="fieldset-label" htmlFor="apps-seller-gender-male">
                                    Male
                                </label>
                                <input
                                    className="radio radio-sm"
                                    value="female"
                                    type="radio"
                                    defaultChecked
                                    name="apps-seller-gender"
                                    id="apps-seller-gender-female"
                                />
                                <label className="fieldset-label" htmlFor="apps-seller-gender-female">
                                    Female
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="card bg-base-100 shadow">
                    <div className="card-body">
                        <div className="card-title">Address</div>
                        <div className="fieldset mt-2 grid grid-cols-1 gap-4 lg:grid-cols-2">
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="street-address">
                                    Street Address
                                </label>
                                <input
                                    type="text"
                                    className="input w-full"
                                    id="street-address"
                                    placeholder="Street Address"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="city">
                                    City
                                </label>
                                <input type="text" className="input w-full" id="city" placeholder="City" />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="state">
                                    State
                                </label>
                                <input type="text" className="input w-full" id="state" placeholder="State" />
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="postal-code">
                                    Postal Code
                                </label>
                                <input type="text" className="input w-full" id="postal-code" placeholder="564-879" />
                            </div>
                            <div className="flex items-center gap-3">
                                <input className="checkbox checkbox-sm" type="checkbox" id="set-as-permanent" />
                                <label className="label" htmlFor="set-as-permanent">
                                    Set as permanent
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="card bg-base-100 shadow">
                    <div className="card-body">
                        <div className="card-title">Upload Image</div>
                        <div className="mt-4">
                            <FileUploader
                                labelIdle={`<div>Drag and Drop your files or <span style="text-decoration: underline">Browse</span></div>`}
                            />
                        </div>
                    </div>
                </div>
                <div className="bg-base-100 card shadow">
                    <div className="card-body gap-0">
                        <div className="card-title">Create Password</div>
                        <div className="fieldset mt-2 grid grid-cols-1 gap-4 lg:grid-cols-2">
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="password">
                                    Password
                                </label>
                                <label className="input w-full focus:outline-0">
                                    <span className="iconify lucide--key-round text-base-content/60 size-4" />
                                    <input
                                        id="password"
                                        className="grow focus:outline-0"
                                        placeholder="Password"
                                        type={showPassword ? "text" : "password"}
                                    />
                                    <button
                                        className="btn btn-xs btn-ghost btn-circle text-base-content/60"
                                        aria-label="Confirm Password"
                                        onClick={() => setShowPassword(!showPassword)}>
                                        {showPassword ? (
                                            <span className="iconify lucide--eye-off size-4" />
                                        ) : (
                                            <span className="iconify lucide--eye size-4" />
                                        )}
                                    </button>
                                </label>
                            </div>
                            <div className="space-y-2">
                                <label className="fieldset-label" htmlFor="confirm-password">
                                    Confirm Password
                                </label>
                                <label className="input w-full focus:outline-0">
                                    <span className="iconify lucide--key-round text-base-content/60 size-4" />
                                    <input
                                        id="confirm-password"
                                        className="grow focus:outline-0"
                                        placeholder="Confirm Password"
                                        type={showPassword ? "text" : "password"}
                                    />
                                    <button
                                        className="btn btn-xs btn-ghost btn-circle text-base-content/60"
                                        aria-label="Confirm Password"
                                        onClick={() => setShowPassword(!showPassword)}>
                                        {showPassword ? (
                                            <span className="iconify lucide--eye-off size-4" />
                                        ) : (
                                            <span className="iconify lucide--eye size-4" />
                                        )}
                                    </button>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
                <Link className="btn btn-sm btn-ghost" to="/apps/ecommerce/sellers">
                    <span className="iconify lucide--x size-4" />
                    Cancel
                </Link>
                <Link className="btn btn-sm btn-primary" to="/apps/ecommerce/sellers">
                    <span className="iconify lucide--check size-4" />
                    Save
                </Link>
            </div>
        </div>
    );
};

// nexus-nuxt-2.3.0/pages/(admin)/apps/ecommerce/sellers/create/CreateSellerForm.vue
<script setup lang="ts">
import FileUploader from "~/components/forms/FileUploader.vue";

let showPassword = false;

const togglePasswordVisibility = () => {
    showPassword = !showPassword;
};
</script>
<template>
    <div>
        <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
            <div class="card bg-base-100 shadow">
                <div class="card-body">
                    <div class="card-title">Basic Information</div>
                    <div class="fieldset mt-2 grid grid-cols-1 gap-4 lg:grid-cols-2">
                        <div class="space-y-2">
                            <label class="fieldset-label" for="name"> Name </label>
                            <input id="name" type="text" class="input w-full" placeholder="Name" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label">Email</label>
                            <input id="email" type="email" class="input w-full" placeholder="Email" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label">Mobile</label>
                            <input type="tel" class="input w-full" placeholder="(098) 765 4321" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label" for="DOB"> DOB </label>
                            <input id="DOB" type="date" class="input w-full" aria-label="DOB" />
                        </div>
                        <div class="flex items-center gap-3">
                            <input id="verified" class="toggle toggle-sm" type="checkbox" />
                            <label class="label" for="verified"> Verified </label>
                        </div>
                        <div class="flex items-center gap-3">
                            <input
                                id="apps-seller-gender-male"
                                class="radio radio-sm"
                                type="radio"
                                value="male"
                                name="apps-seller-gender" />
                            <label class="fieldset-label" for="apps-seller-gender-male"> Male </label>
                            <input
                                id="apps-seller-gender-female"
                                class="radio radio-sm"
                                value="female"
                                type="radio"
                                name="apps-seller-gender" />
                            <label class="fieldset-label" for="apps-seller-gender-female"> Female </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card bg-base-100 shadow">
                <div class="card-body">
                    <div class="card-title">Address</div>
                    <div class="fieldset mt-2 grid grid-cols-1 gap-4 lg:grid-cols-2">
                        <div class="space-y-2">
                            <label class="fieldset-label" for="street-address"> Street Address </label>
                            <input id="street-address" type="text" class="input w-full" placeholder="Street Address" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label" for="city"> City </label>
                            <input id="city" type="text" class="input w-full" placeholder="City" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label" for="state"> State </label>
                            <input id="state" type="text" class="input w-full" placeholder="State" />
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label" for="postal-code"> Postal Code </label>
                            <input id="postal-code" type="text" class="input w-full" placeholder="564-879" />
                        </div>
                        <div class="flex items-center gap-3">
                            <input id="set-as-permanent" class="checkbox checkbox-sm" type="checkbox" />
                            <label class="label" for="set-as-permanent"> Set as permanent </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card bg-base-100 shadow">
                <div class="card-body">
                    <div class="card-title">Upload Image</div>
                    <div class="mt-4">
                        <FileUploader
                            label-idle='<div>Drag and Drop your files or <span style="text-decoration: underline">Browse</span></div>' />
                    </div>
                </div>
            </div>
            <div class="bg-base-100 card shadow">
                <div class="card-body gap-0">
                    <div class="card-title">Create Password</div>
                    <div class="fieldset mt-2 grid grid-cols-1 gap-5 gap-y-3 lg:grid-cols-2">
                        <div class="space-y-2">
                            <label class="fieldset-label" for="password">Password</label>
                            <label class="input w-full focus:outline-0">
                                <span class="iconify lucide--key-round text-base-content/60 size-4"></span>
                                <input
                                    id="password"
                                    class="grow focus:outline-0"
                                    placeholder="Password"
                                    :type="showPassword ? 'text' : 'password'" />
                                <button
                                    aria-label="Password"
                                    class="btn btn-xs btn-ghost btn-circle text-base-content/60"
                                    @click="togglePasswordVisibility">
                                    <span v-if="showPassword">
                                        <span class="iconify lucide--eye-off size-4"></span>
                                    </span>
                                    <span v-else>
                                        <span class="iconify lucide--eye size-4"></span>
                                    </span>
                                </button>
                            </label>
                        </div>
                        <div class="space-y-2">
                            <label class="fieldset-label" for="confirm-password">Confirm Password</label>
                            <label class="input w-full focus:outline-0">
                                <span class="iconify lucide--key-round text-base-content/60 size-4"></span>
                                <input
                                    id="confirm-password"
                                    class="grow focus:outline-0"
                                    placeholder="Confirm Password"
                                    :type="showPassword ? 'text' : 'password'" />
                                <button
                                    aria-label="Confirm Password"
                                    class="btn btn-xs btn-ghost btn-circle"
                                    @click="togglePasswordVisibility">
                                    <span v-if="showPassword">
                                        <span class="iconify lucide--eye-off size-4"></span>
                                    </span>
                                    <span v-else>
                                        <span class="iconify lucide--eye size-4"></span>
                                    </span>
                                </button>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-6 flex justify-end gap-3">
            <NuxtLink class="btn btn-sm btn-ghost" href="/apps/ecommerce/customers">
                <span class="iconify lucide--x size-4"></span>
                Cancel
            </NuxtLink>
            <NuxtLink class="btn btn-sm btn-primary" href="/apps/ecommerce/customers">
                <span class="iconify lucide--check size-4"></span>
                Save
            </NuxtLink>
        </div>
    </div>
</template>
