// nexus-sveltekit-2.3.0/src/routes/(admin)/pages/settings/UserAvatar.svelte
<script lang="ts">
    import FileUploader from "$lib/components/forms/FileUploader.svelte";

    const showModal = () => {
        document.querySelector<HTMLDialogElement>("#page-settings-avatar-modal")?.showModal();
    };
</script>

<div class="avatar group relative size-24 min-w-24 cursor-pointer overflow-hidden rounded-full" onclick={showModal}>
    <div class="bg-base-200 p-1 pb-0">
        <img src="/images/avatars/1.png" alt="Avatar" />
    </div>
    <div
        class="absolute right-0 -bottom-8 left-0 h-6 w-full bg-black/60 text-center text-sm font-medium text-white opacity-0 backdrop-blur-xs transition-all group-hover:bottom-0 group-hover:opacity-100">
        Edit
    </div>
</div>
<dialog id="page-settings-avatar-modal" class="modal">
    <div class="modal-box">
        <div class="flex items-center justify-between">
            <p class="font-medium">Choose Avatar</p>
            <form method="dialog">
                <button class="btn btn-ghost btn-xs btn-circle" aria-label="Close upload file modal">
                    <span class="iconify lucide--x size-4" />
                </button>
            </form>
        </div>
        <div class="mt-4">
            <FileUploader />
            <div class="mt-5 text-end">
                <button class="btn btn-primary btn-sm">
                    <span class="iconify lucide--arrow-up-from-line size-4" />
                    Update
                </button>
            </div>
        </div>
    </div>
    <form method="dialog" class="modal-backdrop">
        <button>close</button>
    </form>
</dialog>

// nexus-react-2.3.0/src/pages/admin/pages/settings/UserAvatar.tsx
import React from "react";

import { FileUploader } from "@/components/forms/FileUploader";

export const UserAvatar = () => {
    return (
        <>
            <div
                className="avatar group relative size-24 min-w-24 cursor-pointer overflow-hidden rounded-full"
                onClick={() => document.querySelector<HTMLDialogElement>("#page-settings-avatar-modal")?.showModal()}>
                <div className="bg-base-200 p-1 pb-0">
                    <img src="/images/avatars/1.png" alt="Avatar" />
                </div>
                <div className="absolute right-0 -bottom-8 left-0 h-6 w-full bg-black/60 text-center text-sm font-medium text-white opacity-0 backdrop-blur-xs transition-all group-hover:bottom-0 group-hover:opacity-100">
                    Edit
                </div>
            </div>
            <dialog id="page-settings-avatar-modal" className="modal">
                <div className="modal-box">
                    <div className="flex items-center justify-between">
                        <p className="font-medium">Choose Avatar</p>
                        <form method="dialog">
                            <button className="btn btn-ghost btn-xs btn-circle" aria-label="Close upload file modal">
                                <span className="iconify lucide--x size-4" />
                            </button>
                        </form>
                    </div>
                    <div className="mt-4">
                        <FileUploader />
                        <div className="mt-5 text-end">
                            <button className="btn btn-primary btn-sm">
                                <span className="iconify lucide--arrow-up-from-line size-4" />
                                Update
                            </button>
                        </div>
                    </div>
                </div>
                <form method="dialog" className="modal-backdrop">
                    <button>close</button>
                </form>
            </dialog>
        </>
    );
};
