// nexus-sveltekit-2.3.0/src/routes/(admin)/apps/gen-ai/content/+page.svelte
<script lang="ts">
    import PageTitle from "$lib/components/PageTitle.svelte";
    import ContentCreationForm from "./ContentCreationForm.svelte";
    import GeneratedContents from "./GeneratedContents.svelte";
</script>

<PageTitle title="Chat" items={[{ label: "Apps" }, { label: "Chat", active: true }]} />
<div class="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-5 2xl:grid-cols-10">
    <div class="xl:col-span-2 2xl:col-span-3">
        <ContentCreationForm />
    </div>
    <div class="xl:col-span-3 2xl:col-span-7">
        <GeneratedContents />
    </div>
</div>

// nexus-react-2.3.0/src/pages/admin/apps/gen-ai/content/index.tsx
import { MetaData } from "@/components/MetaData";
import { PageTitle } from "@/components/PageTitle";

import { ContentCreationForm } from "./ContentCreationForm";
import { GeneratedContents } from "./GeneratedContents";

const AiCreatorPage = () => {
    return (
        <>
            <MetaData title="Content Creator" />

            <PageTitle
                title="Content Creator"
                items={[{ label: "Gen Ai" }, { label: "Content Creator", active: true }]}
            />
            <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-5 2xl:grid-cols-10">
                <div className="xl:col-span-2 2xl:col-span-3">
                    <ContentCreationForm />
                </div>
                <div className="xl:col-span-3 2xl:col-span-7">
                    <GeneratedContents />
                </div>
            </div>
        </>
    );
};

export default AiCreatorPage;
