// nexus-nuxt-2.3.0/pages/(admin)/ui/charts/apex/bar/index.vue
<script setup lang="ts">
import GroupedBarChart from "./GroupedBarChart.vue";
import MarkerWithBarChart from "./MarkerWithBarChart.vue";
import NegativeValueBarChart from "./NegativeValueBarChart.vue";
import StackedBarChart from "./StackedBarChart.vue";

definePageMeta({
    layout: "admin",
});
</script>

<template>
    <div>
        <PageTitle title="Bar Charts" :items="[{ label: 'Apex Charts' }, { label: 'Bar', active: true }]" />

        <div class="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Bar With Markers</div>
                    <MarkerWithBarChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Grouped Bar</div>
                    <GroupedBarChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Stacked Bar</div>
                    <StackedBarChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Negative Value</div>
                    <NegativeValueBarChart />
                </div>
            </div>
        </div>
    </div>
</template>

// nexus-nextjs-2.3.0/src/app/(admin)/ui/charts/apex/bar/page.tsx
import type { Metadata } from "next";

import { PageTitle } from "@/components/PageTitle";

import { GroupedBarChart } from "./GroupedBarChart";
import { MarkerWithBarChart } from "./MarkerWithBarChart";
import { NegativeValueBarChart } from "./NegativeValueBarChart";
import { StackedBarChart } from "./StackedBarChart";

export const metadata: Metadata = {
    title: "Apex Bar Charts",
};

const ChartPage = () => {
    return (
        <>
            <PageTitle title="Bar Charts" items={[{ label: "Apex Charts" }, { label: "Bar", active: true }]} />
            <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Bar With Markers</div>
                        <MarkerWithBarChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Grouped Bar</div>
                        <GroupedBarChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Stacked Bar</div>
                        <StackedBarChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Negative Value</div>
                        <NegativeValueBarChart />
                    </div>
                </div>
            </div>
        </>
    );
};

export default ChartPage;
