// nexus-react@3.0.0/src/components/PageTitle.tsx
import { ReactNode } from "react";
import { Link } from "react-router";

export type IBreadcrumbItem = {
    label: string;
    path?: string;
    active?: boolean;
};

type IPageTitle = {
    items?: IBreadcrumbItem[];
    title: string;
    centerItem?: ReactNode;
};

export const PageTitle = ({ title, items, centerItem }: IPageTitle) => {
    return (
        <div className="flex items-center justify-between">
            <p className="text-lg font-medium">{title}</p>
            {centerItem != null && centerItem}
            <>
                {items && (
                    <div className="breadcrumbs hidden p-0 text-sm sm:inline">
                        <ul>
                            <li>
                                <Link to="/dashboards/ecommerce">Nexus</Link>
                            </li>
                            {items.map((item, index) => {
                                return (
                                    <li key={index} className={`${item.active ? "opacity-80" : ""}`}>
                                        {item.path ? (
                                            <Link key={index + 1} to={item.path}>
                                                {item.label}
                                            </Link>
                                        ) : (
                                            <>{item.label}</>
                                        )}
                                    </li>
                                );
                            })}
                        </ul>
                    </div>
                )}
            </>
        </div>
    );
};

// nexus-nuxt-2.3.0/components/PageTitle.vue
<script lang="ts" setup>
export type IBreadcrumbItem = {
    label: string;
    path?: string;
    active?: boolean;
};

export type IPageTitle = {
    items?: IBreadcrumbItem[];
    title: string;
};

// Define the props
const props = defineProps<IPageTitle>();
</script>

<template>
    <div class="flex items-center justify-between">
        <h3 class="text-lg font-medium">{{ props.title }}</h3>

        <div v-if="$slots.centerItem">
            <slot name="centerItem" />
        </div>

        <div v-if="props.items" class="breadcrumbs hidden p-0 text-sm sm:inline">
            <ul>
                <li>
                    <NuxtLink href="/dashboards/ecommerce">Nexus</NuxtLink>
                </li>
                <!-- Iterate through items with v-for -->
                <li v-for="(item, index) in props.items" :key="index" :class="{ 'opacity-80': item.active }">
                    <!-- Conditional rendering for item path -->
                    <template v-if="item.path">
                        <NuxtLink :href="item.path">{{ item.label }}</NuxtLink>
                    </template>
                    <template v-else>
                        {{ item.label }}
                    </template>
                </li>
            </ul>
        </div>
    </div>
</template>
