// nexus-nuxt-2.3.0/pages/(admin)/ui/charts/apex/area/SelectionAreaChart.vue
<script setup lang="ts">
import type { ApexOptions } from "apexcharts";

const data = [
    {
        x: 1722153590133,
        y: 50,
    },
    {
        x: 1722239990133,
        y: 62,
    },
    {
        x: 1722326390133,
        y: 67,
    },
    {
        x: 1722412790133,
        y: 87,
    },
    {
        x: 1722499190133,
        y: 101,
    },
    {
        x: 1722585590133,
        y: 118,
    },
    {
        x: 1722671990133,
        y: 136,
    },
    {
        x: 1722758390133,
        y: 135,
    },
    {
        x: 1722844790133,
        y: 125,
    },
    {
        x: 1722931190133,
        y: 114,
    },
    {
        x: 1723017590133,
        y: 105,
    },
    {
        x: 1723103990133,
        y: 113,
    },
    {
        x: 1723190390133,
        y: 112,
    },
    {
        x: 1723276790133,
        y: 113,
    },
    {
        x: 1723363190133,
        y: 98,
    },
    {
        x: 1723449590133,
        y: 92,
    },
    {
        x: 1723535990133,
        y: 75,
    },
    {
        x: 1723622390133,
        y: 71,
    },
    {
        x: 1723708790133,
        y: 52,
    },
    {
        x: 1723795190133,
        y: 71,
    },
    {
        x: 1723881590133,
        y: 54,
    },
    {
        x: 1723967990133,
        y: 51,
    },
    {
        x: 1724054390133,
        y: 57,
    },
    {
        x: 1724140790133,
        y: 62,
    },
    {
        x: 1724227190133,
        y: 80,
    },
    {
        x: 1724313590133,
        y: 95,
    },
    {
        x: 1724399990133,
        y: 100,
    },
    {
        x: 1724486390133,
        y: 101,
    },
    {
        x: 1724572790133,
        y: 120,
    },
    {
        x: 1724659190133,
        y: 104,
    },
    {
        x: 1724745590133,
        y: 98,
    },
    {
        x: 1724831990133,
        y: 116,
    },
    {
        x: 1724918390133,
        y: 98,
    },
    {
        x: 1725004790133,
        y: 118,
    },
    {
        x: 1725091190133,
        y: 113,
    },
    {
        x: 1725177590133,
        y: 122,
    },
    {
        x: 1725263990133,
        y: 141,
    },
    {
        x: 1725350390133,
        y: 145,
    },
    {
        x: 1725436790133,
        y: 160,
    },
    {
        x: 1725523190133,
        y: 151,
    },
    {
        x: 1725609590133,
        y: 165,
    },
    {
        x: 1725695990133,
        y: 154,
    },
    {
        x: 1725782390133,
        y: 141,
    },
    {
        x: 1725868790133,
        y: 127,
    },
    {
        x: 1725955190133,
        y: 147,
    },
    {
        x: 1726041590133,
        y: 142,
    },
    {
        x: 1726127990133,
        y: 148,
    },
    {
        x: 1726214390133,
        y: 166,
    },
    {
        x: 1726300790133,
        y: 163,
    },
    {
        x: 1726387190133,
        y: 147,
    },
    {
        x: 1726473590133,
        y: 134,
    },
    {
        x: 1726559990133,
        y: 121,
    },
    {
        x: 1726646390133,
        y: 129,
    },
    {
        x: 1726732790133,
        y: 124,
    },
    {
        x: 1726819190133,
        y: 111,
    },
    {
        x: 1726905590133,
        y: 112,
    },
    {
        x: 1726991990133,
        y: 110,
    },
    {
        x: 1727078390133,
        y: 95,
    },
    {
        x: 1727164790133,
        y: 99,
    },
    {
        x: 1727251190133,
        y: 82,
    },
    {
        x: 1727337590133,
        y: 69,
    },
    {
        x: 1727423990133,
        y: 74,
    },
    {
        x: 1727510390133,
        y: 61,
    },
    {
        x: 1727596790133,
        y: 74,
    },
    {
        x: 1727683190133,
        y: 85,
    },
    {
        x: 1727769590133,
        y: 74,
    },
    {
        x: 1727855990133,
        y: 92,
    },
    {
        x: 1727942390133,
        y: 73,
    },
    {
        x: 1728028790133,
        y: 59,
    },
    {
        x: 1728115190133,
        y: 54,
    },
    {
        x: 1728201590133,
        y: 53,
    },
    {
        x: 1728287990133,
        y: 65,
    },
    {
        x: 1728374390133,
        y: 53,
    },
    {
        x: 1728460790133,
        y: 69,
    },
    {
        x: 1728547190133,
        y: 61,
    },
    {
        x: 1728633590133,
        y: 65,
    },
    {
        x: 1728719990133,
        y: 63,
    },
    {
        x: 1728806390133,
        y: 66,
    },
    {
        x: 1728892790133,
        y: 67,
    },
    {
        x: 1728979190133,
        y: 56,
    },
    {
        x: 1729065590133,
        y: 61,
    },
    {
        x: 1729151990133,
        y: 62,
    },
    {
        x: 1729238390133,
        y: 50,
    },
    {
        x: 1729324790133,
        y: 69,
    },
    {
        x: 1729411190133,
        y: 82,
    },
    {
        x: 1729497590133,
        y: 79,
    },
    {
        x: 1729583990133,
        y: 99,
    },
    {
        x: 1729670390133,
        y: 101,
    },
    {
        x: 1729756790133,
        y: 120,
    },
    {
        x: 1729843190133,
        y: 134,
    },
    {
        x: 1729929590133,
        y: 151,
    },
    {
        x: 1730015990133,
        y: 152,
    },
    {
        x: 1730102390133,
        y: 148,
    },
    {
        x: 1730188790133,
        y: 130,
    },
    {
        x: 1730275190133,
        y: 123,
    },
    {
        x: 1730361590133,
        y: 119,
    },
    {
        x: 1730447990133,
        y: 107,
    },
    {
        x: 1730534390133,
        y: 102,
    },
    {
        x: 1730620790133,
        y: 90,
    },
    {
        x: 1730707190133,
        y: 91,
    },
    {
        x: 1730793590133,
        y: 101,
    },
    {
        x: 1730879990133,
        y: 91,
    },
    {
        x: 1730966390133,
        y: 99,
    },
    {
        x: 1731052790133,
        y: 92,
    },
    {
        x: 1731139190133,
        y: 105,
    },
    {
        x: 1731225590133,
        y: 96,
    },
    {
        x: 1731311990133,
        y: 93,
    },
    {
        x: 1731398390133,
        y: 78,
    },
    {
        x: 1731484790133,
        y: 69,
    },
    {
        x: 1731571190133,
        y: 51,
    },
    {
        x: 1731657590133,
        y: 52,
    },
    {
        x: 1731743990133,
        y: 65,
    },
    {
        x: 1731830390133,
        y: 52,
    },
    {
        x: 1731916790133,
        y: 70,
    },
    {
        x: 1732003190133,
        y: 90,
    },
    {
        x: 1732089590133,
        y: 91,
    },
    {
        x: 1732175990133,
        y: 88,
    },
    {
        x: 1732262390133,
        y: 75,
    },
    {
        x: 1732348790133,
        y: 67,
    },
    {
        x: 1732435190133,
        y: 70,
    },
    {
        x: 1732521590133,
        y: 69,
    },
    {
        x: 1732607990133,
        y: 56,
    },
    {
        x: 1732694390133,
        y: 51,
    },
    {
        x: 1732780790133,
        y: 65,
    },
    {
        x: 1732867190133,
        y: 69,
    },
    {
        x: 1732953590133,
        y: 65,
    },
    {
        x: 1733039990133,
        y: 68,
    },
    {
        x: 1733126390133,
        y: 73,
    },
    {
        x: 1733212790133,
        y: 88,
    },
    {
        x: 1733299190133,
        y: 100,
    },
    {
        x: 1733385590133,
        y: 112,
    },
    {
        x: 1733471990133,
        y: 122,
    },
    {
        x: 1733558390133,
        y: 131,
    },
    {
        x: 1733644790133,
        y: 133,
    },
    {
        x: 1733731190133,
        y: 130,
    },
    {
        x: 1733817590133,
        y: 136,
    },
    {
        x: 1733903990133,
        y: 128,
    },
    {
        x: 1733990390133,
        y: 136,
    },
    {
        x: 1734076790133,
        y: 145,
    },
    {
        x: 1734163190133,
        y: 149,
    },
    {
        x: 1734249590133,
        y: 150,
    },
    {
        x: 1734335990133,
        y: 153,
    },
    {
        x: 1734422390133,
        y: 171,
    },
    {
        x: 1734508790133,
        y: 152,
    },
    {
        x: 1734595190133,
        y: 163,
    },
    {
        x: 1734681590133,
        y: 150,
    },
    {
        x: 1734767990133,
        y: 149,
    },
    {
        x: 1734854390133,
        y: 141,
    },
    {
        x: 1734940790133,
        y: 161,
    },
    {
        x: 1735027190133,
        y: 177,
    },
    {
        x: 1735113590133,
        y: 178,
    },
    {
        x: 1735199990133,
        y: 178,
    },
    {
        x: 1735286390133,
        y: 184,
    },
    {
        x: 1735372790133,
        y: 193,
    },
];

const resultChartOptions: ApexOptions = {
    series: [
        {
            name: "Visitors",
            data: data,
        },
    ],
    chart: {
        id: "result-chart",
        height: 190,
        type: "area",
        background: "transparent",
        toolbar: {
            show: true,
            tools: {
                download: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
        },
    },
    colors: ["#FDA403"],
    stroke: {
        width: 2,
        curve: "smooth",
    },
    dataLabels: {
        enabled: false,
    },
    fill: {
        opacity: 0.6,
        type: "solid",
    },
    xaxis: {
        type: "datetime",
    },
};

const targetChartOptions: ApexOptions = {
    series: [
        {
            name: "Visitors",
            data: data,
        },
    ],
    chart: {
        height: 190,
        type: "area",
        background: "transparent",
        toolbar: {
            show: true,
            tools: {
                download: true,
                selection: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
            autoSelected: "selection",
        },
        brush: {
            enabled: true,
            target: "result-chart",
        },
        selection: {
            enabled: true,
            fill: {
                color: "#FDA403",
                opacity: 0.3,
            },
            stroke: {
                width: 2,
                color: "#FDA403",
                opacity: 0.8,
                dashArray: 3,
            },
            xaxis: {
                min: new Date().getTime() - 15 * 60 * 1000 * 1000,
                max: new Date().getTime(),
            },
        },
    },
    colors: ["#167bff"],
    dataLabels: {
        enabled: false,
    },
    stroke: {
        width: 2,
        curve: "smooth",
    },
    fill: {
        opacity: 0.6,
        type: "solid",
    },
    xaxis: {
        type: "datetime",
    },
};

const chart1Ref = ref<HTMLDivElement | null>(null);
const chart2Ref = ref<HTMLDivElement | null>(null);

onMounted(async () => {
    const ApexCharts = (await import("apexcharts")).default;
    if (chart1Ref.value && chart2Ref.value) {
        new ApexCharts(chart1Ref.value, resultChartOptions).render();
        new ApexCharts(chart2Ref.value, targetChartOptions).render();
    }
});
</script>

<template>
    <div>
        <div ref="chart1Ref"></div>
        <div ref="chart2Ref"></div>
    </div>
</template>

// nexus-react@3.0.0/src/pages/components/apex-charts/area/SelectionAreaChart.tsx
import type { ApexOptions } from "apexcharts";
import { Suspense, lazy, useEffect, useState } from "react";

import { LoadingEffect } from "@/components/LoadingEffect";

const ApexCharts = lazy(() => import("react-apexcharts"));

const data = [
    {
        x: 1722153590133,
        y: 50,
    },
    {
        x: 1722239990133,
        y: 62,
    },
    {
        x: 1722326390133,
        y: 67,
    },
    {
        x: 1722412790133,
        y: 87,
    },
    {
        x: 1722499190133,
        y: 101,
    },
    {
        x: 1722585590133,
        y: 118,
    },
    {
        x: 1722671990133,
        y: 136,
    },
    {
        x: 1722758390133,
        y: 135,
    },
    {
        x: 1722844790133,
        y: 125,
    },
    {
        x: 1722931190133,
        y: 114,
    },
    {
        x: 1723017590133,
        y: 105,
    },
    {
        x: 1723103990133,
        y: 113,
    },
    {
        x: 1723190390133,
        y: 112,
    },
    {
        x: 1723276790133,
        y: 113,
    },
    {
        x: 1723363190133,
        y: 98,
    },
    {
        x: 1723449590133,
        y: 92,
    },
    {
        x: 1723535990133,
        y: 75,
    },
    {
        x: 1723622390133,
        y: 71,
    },
    {
        x: 1723708790133,
        y: 52,
    },
    {
        x: 1723795190133,
        y: 71,
    },
    {
        x: 1723881590133,
        y: 54,
    },
    {
        x: 1723967990133,
        y: 51,
    },
    {
        x: 1724054390133,
        y: 57,
    },
    {
        x: 1724140790133,
        y: 62,
    },
    {
        x: 1724227190133,
        y: 80,
    },
    {
        x: 1724313590133,
        y: 95,
    },
    {
        x: 1724399990133,
        y: 100,
    },
    {
        x: 1724486390133,
        y: 101,
    },
    {
        x: 1724572790133,
        y: 120,
    },
    {
        x: 1724659190133,
        y: 104,
    },
    {
        x: 1724745590133,
        y: 98,
    },
    {
        x: 1724831990133,
        y: 116,
    },
    {
        x: 1724918390133,
        y: 98,
    },
    {
        x: 1725004790133,
        y: 118,
    },
    {
        x: 1725091190133,
        y: 113,
    },
    {
        x: 1725177590133,
        y: 122,
    },
    {
        x: 1725263990133,
        y: 141,
    },
    {
        x: 1725350390133,
        y: 145,
    },
    {
        x: 1725436790133,
        y: 160,
    },
    {
        x: 1725523190133,
        y: 151,
    },
    {
        x: 1725609590133,
        y: 165,
    },
    {
        x: 1725695990133,
        y: 154,
    },
    {
        x: 1725782390133,
        y: 141,
    },
    {
        x: 1725868790133,
        y: 127,
    },
    {
        x: 1725955190133,
        y: 147,
    },
    {
        x: 1726041590133,
        y: 142,
    },
    {
        x: 1726127990133,
        y: 148,
    },
    {
        x: 1726214390133,
        y: 166,
    },
    {
        x: 1726300790133,
        y: 163,
    },
    {
        x: 1726387190133,
        y: 147,
    },
    {
        x: 1726473590133,
        y: 134,
    },
    {
        x: 1726559990133,
        y: 121,
    },
    {
        x: 1726646390133,
        y: 129,
    },
    {
        x: 1726732790133,
        y: 124,
    },
    {
        x: 1726819190133,
        y: 111,
    },
    {
        x: 1726905590133,
        y: 112,
    },
    {
        x: 1726991990133,
        y: 110,
    },
    {
        x: 1727078390133,
        y: 95,
    },
    {
        x: 1727164790133,
        y: 99,
    },
    {
        x: 1727251190133,
        y: 82,
    },
    {
        x: 1727337590133,
        y: 69,
    },
    {
        x: 1727423990133,
        y: 74,
    },
    {
        x: 1727510390133,
        y: 61,
    },
    {
        x: 1727596790133,
        y: 74,
    },
    {
        x: 1727683190133,
        y: 85,
    },
    {
        x: 1727769590133,
        y: 74,
    },
    {
        x: 1727855990133,
        y: 92,
    },
    {
        x: 1727942390133,
        y: 73,
    },
    {
        x: 1728028790133,
        y: 59,
    },
    {
        x: 1728115190133,
        y: 54,
    },
    {
        x: 1728201590133,
        y: 53,
    },
    {
        x: 1728287990133,
        y: 65,
    },
    {
        x: 1728374390133,
        y: 53,
    },
    {
        x: 1728460790133,
        y: 69,
    },
    {
        x: 1728547190133,
        y: 61,
    },
    {
        x: 1728633590133,
        y: 65,
    },
    {
        x: 1728719990133,
        y: 63,
    },
    {
        x: 1728806390133,
        y: 66,
    },
    {
        x: 1728892790133,
        y: 67,
    },
    {
        x: 1728979190133,
        y: 56,
    },
    {
        x: 1729065590133,
        y: 61,
    },
    {
        x: 1729151990133,
        y: 62,
    },
    {
        x: 1729238390133,
        y: 50,
    },
    {
        x: 1729324790133,
        y: 69,
    },
    {
        x: 1729411190133,
        y: 82,
    },
    {
        x: 1729497590133,
        y: 79,
    },
    {
        x: 1729583990133,
        y: 99,
    },
    {
        x: 1729670390133,
        y: 101,
    },
    {
        x: 1729756790133,
        y: 120,
    },
    {
        x: 1729843190133,
        y: 134,
    },
    {
        x: 1729929590133,
        y: 151,
    },
    {
        x: 1730015990133,
        y: 152,
    },
    {
        x: 1730102390133,
        y: 148,
    },
    {
        x: 1730188790133,
        y: 130,
    },
    {
        x: 1730275190133,
        y: 123,
    },
    {
        x: 1730361590133,
        y: 119,
    },
    {
        x: 1730447990133,
        y: 107,
    },
    {
        x: 1730534390133,
        y: 102,
    },
    {
        x: 1730620790133,
        y: 90,
    },
    {
        x: 1730707190133,
        y: 91,
    },
    {
        x: 1730793590133,
        y: 101,
    },
    {
        x: 1730879990133,
        y: 91,
    },
    {
        x: 1730966390133,
        y: 99,
    },
    {
        x: 1731052790133,
        y: 92,
    },
    {
        x: 1731139190133,
        y: 105,
    },
    {
        x: 1731225590133,
        y: 96,
    },
    {
        x: 1731311990133,
        y: 93,
    },
    {
        x: 1731398390133,
        y: 78,
    },
    {
        x: 1731484790133,
        y: 69,
    },
    {
        x: 1731571190133,
        y: 51,
    },
    {
        x: 1731657590133,
        y: 52,
    },
    {
        x: 1731743990133,
        y: 65,
    },
    {
        x: 1731830390133,
        y: 52,
    },
    {
        x: 1731916790133,
        y: 70,
    },
    {
        x: 1732003190133,
        y: 90,
    },
    {
        x: 1732089590133,
        y: 91,
    },
    {
        x: 1732175990133,
        y: 88,
    },
    {
        x: 1732262390133,
        y: 75,
    },
    {
        x: 1732348790133,
        y: 67,
    },
    {
        x: 1732435190133,
        y: 70,
    },
    {
        x: 1732521590133,
        y: 69,
    },
    {
        x: 1732607990133,
        y: 56,
    },
    {
        x: 1732694390133,
        y: 51,
    },
    {
        x: 1732780790133,
        y: 65,
    },
    {
        x: 1732867190133,
        y: 69,
    },
    {
        x: 1732953590133,
        y: 65,
    },
    {
        x: 1733039990133,
        y: 68,
    },
    {
        x: 1733126390133,
        y: 73,
    },
    {
        x: 1733212790133,
        y: 88,
    },
    {
        x: 1733299190133,
        y: 100,
    },
    {
        x: 1733385590133,
        y: 112,
    },
    {
        x: 1733471990133,
        y: 122,
    },
    {
        x: 1733558390133,
        y: 131,
    },
    {
        x: 1733644790133,
        y: 133,
    },
    {
        x: 1733731190133,
        y: 130,
    },
    {
        x: 1733817590133,
        y: 136,
    },
    {
        x: 1733903990133,
        y: 128,
    },
    {
        x: 1733990390133,
        y: 136,
    },
    {
        x: 1734076790133,
        y: 145,
    },
    {
        x: 1734163190133,
        y: 149,
    },
    {
        x: 1734249590133,
        y: 150,
    },
    {
        x: 1734335990133,
        y: 153,
    },
    {
        x: 1734422390133,
        y: 171,
    },
    {
        x: 1734508790133,
        y: 152,
    },
    {
        x: 1734595190133,
        y: 163,
    },
    {
        x: 1734681590133,
        y: 150,
    },
    {
        x: 1734767990133,
        y: 149,
    },
    {
        x: 1734854390133,
        y: 141,
    },
    {
        x: 1734940790133,
        y: 161,
    },
    {
        x: 1735027190133,
        y: 177,
    },
    {
        x: 1735113590133,
        y: 178,
    },
    {
        x: 1735199990133,
        y: 178,
    },
    {
        x: 1735286390133,
        y: 184,
    },
    {
        x: 1735372790133,
        y: 193,
    },
];

const resultChartOptions: ApexOptions = {
    series: [
        {
            name: "Visitors",
            data: data,
        },
    ],
    chart: {
        id: "result-chart",
        height: 190,
        type: "area",
        background: "transparent",
        toolbar: {
            show: true,
            tools: {
                download: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
        },
    },
    colors: ["#FDA403"],
    stroke: {
        width: 2,
        curve: "smooth",
    },
    dataLabels: {
        enabled: false,
    },
    fill: {
        opacity: 0.6,
        type: "solid",
    },
    xaxis: {
        type: "datetime",
    },
};

const targetChartOptions: ApexOptions = {
    series: [
        {
            name: "Visitors",
            data: data,
        },
    ],
    chart: {
        height: 190,
        type: "area",
        background: "transparent",
        toolbar: {
            show: true,
            tools: {
                download: true,
                selection: true,
                zoom: false,
                zoomin: false,
                zoomout: false,
                pan: false,
                reset: false,
            },
            autoSelected: "selection",
        },
        brush: {
            enabled: true,
            target: "result-chart",
        },
        selection: {
            enabled: true,
            fill: {
                color: "#FDA403",
                opacity: 0.3,
            },
            stroke: {
                width: 2,
                color: "#FDA403",
                opacity: 0.8,
                dashArray: 3,
            },
            xaxis: {
                min: 1726041590133,
                max: 1726041590133 + 15 * 60 * 1000 * 1000,
            },
        },
    },
    colors: ["#167bff"],
    dataLabels: {
        enabled: false,
    },
    stroke: {
        width: 2,
        curve: "smooth",
    },
    fill: {
        opacity: 0.6,
        type: "solid",
    },
    xaxis: {
        type: "datetime",
    },
};

export const SelectionAreaChart = () => {
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) return <LoadingEffect height={380} />;

    return (
        <Suspense fallback={<LoadingEffect height={380} />}>
            <div>
                <ApexCharts
                    options={resultChartOptions}
                    type={resultChartOptions.chart?.type}
                    height={resultChartOptions.chart?.height}
                    series={resultChartOptions.series}
                />
                <ApexCharts
                    options={targetChartOptions}
                    type={targetChartOptions.chart?.type}
                    height={targetChartOptions.chart?.height}
                    series={targetChartOptions.series}
                />
            </div>
        </Suspense>
    );
};
