// nexus-nextjs-2.3.0/src/app/(admin)/ui/charts/apex/line/page.tsx
import type { Metadata } from "next";

import { PageTitle } from "@/components/PageTitle";

import { AnnotationLineChart } from "./AnnotationLineChart";
import { LabelLineChart } from "./LabelLineChart";
import { StepLineChart } from "./StepLineChart";
import { SyncingLineChart } from "./SyncingLineChart";

export const metadata: Metadata = {
    title: "Apex Line Charts",
};

const ChartPage = () => {
    return (
        <>
            <PageTitle title="Line Charts" items={[{ label: "Apex Charts" }, { label: "Line", active: true }]} />
            <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Label Line</div>
                        <LabelLineChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Step Line</div>
                        <StepLineChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Syncing Line</div>
                        <SyncingLineChart />
                    </div>
                </div>
                <div className="card card-border bg-base-100">
                    <div className="card-body gap-3 pb-0">
                        <div className="card-title">Annotation Line</div>
                        <AnnotationLineChart />
                    </div>
                </div>
            </div>
        </>
    );
};

export default ChartPage;

// nexus-nuxt-2.3.0/pages/(admin)/ui/charts/apex/line/index.vue
<script setup lang="ts">
import AnnotationLineChart from "./AnnotationLineChart.vue";
import LabelLineChart from "./LabelLineChart.vue";
import StepLineChart from "./StepLineChart.vue";
import SyncingLineChart from "./SyncingLineChart.vue";

definePageMeta({
    layout: "admin",
});
</script>

<template>
    <div>
        <PageTitle title="Line Charts" :items="[{ label: 'Apex Charts' }, { label: 'Line', active: true }]" />

        <div class="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2">
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Label Line</div>
                    <LabelLineChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Step Line</div>
                    <StepLineChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Syncing Line</div>
                    <SyncingLineChart />
                </div>
            </div>
            <div class="card card-border bg-base-100">
                <div class="card-body gap-3 pb-0">
                    <div class="card-title">Annotation Line</div>
                    <AnnotationLineChart />
                </div>
            </div>
        </div>
    </div>
</template>
